"""
Regenerate ``aportalsmp/utils/collections_ids.py`` from the live Portals API.

The ``/collections`` endpoint is public (no auth required), so this script can be
run any time new gifts are released:

    python scripts/update_collections.py

It rewrites the ``collections_ids`` mapping (gift name -> collection UUID) using
the exact names returned by the API, which keeps model/backdrop/name lookups in
sync with the marketplace.
"""
from __future__ import annotations

import os
import sys

try:
    from curl_cffi import requests as curl_requests
except ImportError:  # pragma: no cover
    sys.exit("curl_cffi is required: pip install curl_cffi")

API_URL = "https://portal-market.com/api/collections?limit=1000"
OUT_PATH = os.path.join(
    os.path.dirname(os.path.dirname(os.path.abspath(__file__))),
    "aportalsmp", "utils", "collections_ids.py",
)

HEADERS = {
    "Accept": "application/json, text/plain, */*",
    "Origin": "https://portal-market.com",
    "Referer": "https://portal-market.com/",
}

HEADER_COMMENT = (
    "# Auto-generated by scripts/update_collections.py from the public\n"
    "# https://portal-market.com/api/collections endpoint. Do not edit by hand;\n"
    "# re-run the script to refresh the list when new gifts are released.\n"
)


def fetch_collections() -> list[dict]:
    resp = curl_requests.get(API_URL, headers=HEADERS, impersonate="chrome110", timeout=30)
    resp.raise_for_status()
    data = resp.json()
    collections = data.get("collections", data if isinstance(data, list) else [])
    if not collections:
        sys.exit("No collections returned from the API.")
    return collections


def render(collections: list[dict]) -> str:
    # Preserve the marketplace ordering; de-duplicate by name (keep first).
    seen: dict[str, str] = {}
    for c in collections:
        name, cid = c.get("name"), c.get("id")
        if name and cid and name not in seen:
            seen[name] = cid

    lines = [HEADER_COMMENT, "collections_ids = {"]
    for name, cid in seen.items():
        # repr() keeps unicode apostrophes (e.g. Durov's Cap) intact and safely escaped.
        lines.append(f"    {name!r}: {cid!r},")
    lines.append("}")
    lines.append("")
    # short_name-normalised lookup table for robust name resolution
    lines.append("from .functions import toShortName as _toShortName")
    lines.append("")
    lines.append("short_name_ids = {_toShortName(_n): _id for _n, _id in collections_ids.items()}")
    lines.append("")
    return "\n".join(lines)


def main() -> None:
    collections = fetch_collections()
    content = render(collections)
    with open(OUT_PATH, "w", encoding="utf-8") as f:
        f.write(content)
    print(f"Wrote {len(collections)} collections -> {OUT_PATH}")


if __name__ == "__main__":
    main()
